server {
    listen 80;
    server_name _;
    client_max_body_size 20M;

    gzip on;
    gzip_buffers 32 4K;
    gzip_comp_level 6;
    gzip_min_length 100;
    gzip_types application/javascript text/css text/xml application/json;
    gzip_disable "MSIE [1-6]\.";
    gzip_vary on;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
